import Anthropic from "@anthropic-ai/sdk";
import { prisma } from "@/lib/db";

// AI generation of a DiagnosticAdvice from a user's abnormal metrics (passed from
// the client) + historical cases (server-side visits/reports/vitals). Mirrors
// lib/wellness-plan.ts: fire-and-forget, writes the result back onto the row and
// flips status to done/failed. The model is asked for a strict JSON
// { assessment, alert, followUp } object; on parse failure the raw text goes into
// assessmentText so the user still sees something.

const MODEL = process.env.ANTHROPIC_MODEL || "claude-opus-5";

function systemPrompt(zh: boolean): string {
  return zh
    ? `你是 Medicompass（迈缔康）的健康管理助手。基于用户的「异常指标」与「历史病例」（门诊/住院就诊、报告解读、监测指标、Apple 健康数据），做诊疗风险研判与就诊提示。
要求：严格基于所给材料，不臆测、不编造，材料未提及处不强行给结论；语气务实、克制、可执行。
仅输出一个 JSON 对象，不要额外文字或代码块围栏，格式：
{"assessment":"……","alert":"……","followUp":"……"}
- assessment（病情发展研判）：结合异常指标与既往诊断，研判病情可能的发展方向与风险；材料不足处明确说明。
- alert（预警与建议就诊科室）：指出需要警惕的信号，并建议尽快就诊的**具体科室**（如心内科、内分泌科、呼吸科等），并简述理由。
- followUp（复诊与定期监测）：先判断就诊/报告记录里**是否已做过对应检查**——若已做过，给出复诊时机与需要定期监测的指标及频率；若未见相关检查，则明确提示尽快到 alert 所列科室做首次检查。
每部分末尾附一句「本建议由 AI 依据所提供材料生成，不构成医疗诊断，请结合医生意见。」`
    : `You are the Medicompass health-management assistant. Based on the user's abnormal metrics and historical cases (outpatient/inpatient visits, report readings, tracked vitals, Apple Health data), produce a diagnostic risk assessment and care prompts.
Ground everything strictly in the material; do not fabricate; state where the material is silent. Keep the tone practical, measured, actionable.
Output ONLY a single JSON object, no extra text or code fences, in the form:
{"assessment":"…","alert":"…","followUp":"…"}
- assessment (disease-progression judgment): combining abnormal metrics with prior diagnoses, assess likely progression and risk; note gaps in the material.
- alert (early warning + which department): flag warning signs and recommend the specific department to be checked at soon (e.g. cardiology, endocrinology, pulmonology), with a brief rationale.
- followUp (recheck & monitoring): first decide whether the relevant check was already done per the visit/report records — if so, give recheck timing plus which metrics to monitor regularly and how often; if no relevant check is found, clearly prompt getting the first check at the department named in alert soon.
End each section with: "This advice was generated by AI from the provided material, is not a medical diagnosis, and should be confirmed with your doctor."`;
}

function ageFrom(birthDate: Date | null): string {
  if (!birthDate) return "";
  const ms = Date.now() - birthDate.getTime();
  const years = Math.floor(ms / (365.25 * 24 * 3600 * 1000));
  return years > 0 && years < 130 ? `${years}` : "";
}

async function buildContext(
  userId: string,
  zh: boolean,
  abnormalContext?: string,
  healthContext?: string,
): Promise<string> {
  const [user, meds, visits, reports, vitals] = await Promise.all([
    prisma.mobileUser.findUnique({ where: { id: userId } }),
    prisma.mobileMedication.findMany({ where: { userId } }),
    prisma.mobileVisit.findMany({ where: { userId }, orderBy: { visitDate: "desc" }, take: 5 }),
    prisma.mobileReport.findMany({ where: { userId }, orderBy: { createdAt: "desc" }, take: 5 }),
    prisma.mobileVitalReading.findMany({ where: { userId }, orderBy: { measuredAt: "desc" }, take: 20 }),
  ]);

  const lines: string[] = [];

  // Abnormal metrics come first — they are the trigger for this advice and are
  // computed on the client from the same server-backed data.
  if (abnormalContext && abnormalContext.trim()) {
    lines.push(zh ? "当前异常指标（用户侧判定）：" : "Current abnormal metrics (client-side):");
    lines.push(abnormalContext.trim());
  }

  if (user) {
    const age = ageFrom(user.birthDate);
    const basics = [
      user.gender ? (zh ? `性别 ${user.gender}` : `sex ${user.gender}`) : "",
      age ? (zh ? `年龄 ${age}` : `age ${age}`) : "",
      user.bloodType ? (zh ? `血型 ${user.bloodType}` : `blood ${user.bloodType}`) : "",
    ].filter(Boolean).join("，");
    if (basics) lines.push((zh ? "基础信息：" : "Basics: ") + basics);
    if (user.allergies) lines.push((zh ? "过敏史：" : "Allergies: ") + user.allergies);
    if (user.medicalHistory) lines.push((zh ? "既往史：" : "History: ") + user.medicalHistory);
  }
  if (meds.length) {
    lines.push(zh ? "用药计划：" : "Medications:");
    for (const m of meds) lines.push(`- ${zh ? m.nameZh : m.nameEn} ${m.dosage} ${zh ? m.timingZh : m.timingEn}`);
  }
  if (visits.length) {
    lines.push(zh ? "就诊记录（含门诊/住院/体检）：" : "Visits (outpatient/inpatient/checkup):");
    for (const v of visits) {
      lines.push(`- ${v.visitDate.toISOString().slice(0, 10)} [${v.visitType}] ${v.department} ${v.diagnosis || v.hospital || ""}`.trim());
    }
  }
  if (reports.length) {
    lines.push(zh ? "报告解读：" : "Report readings:");
    for (const r of reports) {
      if (r.aiStatus === "done" && r.aiInterpretation) {
        lines.push(`- ${r.category}: ${r.aiInterpretation.replace(/\s+/g, " ").slice(0, 300)}`);
      }
    }
  }
  if (vitals.length) {
    lines.push(zh ? "监测指标：" : "Tracked vitals:");
    for (const r of vitals) {
      const sec = r.secondary != null ? `/${r.secondary}` : "";
      lines.push(`- ${r.kind} ${r.value}${sec} @ ${r.measuredAt.toISOString().slice(0, 10)}`);
    }
  }
  if (healthContext && healthContext.trim()) {
    lines.push(zh ? "Apple 健康数据：" : "Apple Health data:");
    lines.push(healthContext.trim());
  }
  return lines.join("\n") || (zh ? "（暂无记录）" : "(no records yet)");
}

export async function generateDiagnosticAdvice(
  adviceId: string,
  userId: string,
  locale: string,
  abnormalContext?: string,
  healthContext?: string,
): Promise<void> {
  const zh = (locale || "").startsWith("zh");
  try {
    if (!process.env.ANTHROPIC_API_KEY) throw new Error("Missing ANTHROPIC_API_KEY");

    const context = await buildContext(userId, zh, abnormalContext, healthContext);
    const client = new Anthropic({ baseURL: process.env.ANTHROPIC_BASE_URL || undefined });
    const msg = await client.messages.create({
      model: MODEL,
      max_tokens: 1400,
      system: systemPrompt(zh),
      messages: [
        { role: "user", content: (zh ? "以下是该用户的异常指标与历史病例：\n" : "Here are the user's abnormal metrics and historical cases:\n") + context },
      ],
    });
    const text = msg.content
      .filter((b): b is Anthropic.TextBlock => b.type === "text")
      .map((b) => b.text)
      .join("")
      .trim();

    let assessment = "";
    let alert = "";
    let followUp = "";
    // Model is asked for a bare JSON object; tolerate stray prose/fences.
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      try {
        const parsed = JSON.parse(jsonMatch[0]) as { assessment?: string; alert?: string; followUp?: string };
        assessment = (parsed.assessment || "").trim();
        alert = (parsed.alert || "").trim();
        followUp = (parsed.followUp || "").trim();
      } catch {
        // fall through to raw
      }
    }
    if (!assessment && !alert && !followUp) assessment = text; // parse failed: keep raw

    await prisma.diagnosticAdvice.update({
      where: { id: adviceId },
      data: { assessmentText: assessment, alertText: alert, followUpText: followUp, status: "done", error: null },
    });
  } catch (err) {
    await prisma.diagnosticAdvice.update({
      where: { id: adviceId },
      data: { status: "failed", error: err instanceof Error ? err.message : String(err) },
    });
  }
}
