import { promises as fs } from "fs";
import Anthropic from "@anthropic-ai/sdk";
import { prisma } from "@/lib/db";

// AI interpretation of a single uploaded MobileReport (PDF or image). Mirrors
// lib/ai.ts but writes to the MobileReport row and produces a consumer-facing,
// bilingual-aware reading with a mandatory disclaimer. Fire-and-forget safe.

const MODEL = process.env.ANTHROPIC_MODEL || "claude-opus-5";

const SUPPORTED_DOC = new Set(["application/pdf"]);
const SUPPORTED_IMG = new Set(["image/png", "image/jpeg", "image/webp"]);

type Block =
  | { type: "text"; text: string }
  | { type: "document"; source: { type: "base64"; media_type: "application/pdf"; data: string } }
  | {
      type: "image";
      source: { type: "base64"; media_type: "image/png" | "image/jpeg" | "image/webp"; data: string };
    };

function systemPrompt(zh: boolean): string {
  return zh
    ? `你是 Medicompass 健康助手，帮助用户读懂体检/检验报告。请仅依据报告内容，用简体中文输出：
一、总体印象（1-2 句）
二、值得关注的指标（逐条：指标—数值—是否偏离参考范围—通俗解释）
三、今日可执行建议（2-3 条）
严格基于材料，不臆测；材料未提及的写「未提供」。
末尾附一行：「本解读由 AI 依据所提供材料自动生成，不构成医疗诊断，请结合医生意见。」`
    : `You are the Medicompass health assistant helping a user understand a screening/lab report.
Using ONLY the report content, output in English:
1. Overall impression (1-2 sentences)
2. Values worth attention (per line: metric — value — in/out of reference range — plain explanation)
3. Actionable suggestions for today (2-3 bullets)
Stay strictly grounded in the material; write "not provided" for anything missing.
End with: "This reading was generated by AI from the provided material, is not a medical diagnosis, and should be confirmed with your doctor."`;
}

export async function interpretReport(reportId: string, locale: string): Promise<void> {
  const report = await prisma.mobileReport.findUnique({ where: { id: reportId } });
  if (!report) return;
  const zh = (locale || "").startsWith("zh");

  try {
    if (!process.env.ANTHROPIC_API_KEY) {
      throw new Error("Missing ANTHROPIC_API_KEY");
    }

    const blocks: Block[] = [
      { type: "text", text: zh ? "请解读以下体检/检验报告。" : "Please interpret the following screening/lab report." },
    ];

    if (SUPPORTED_DOC.has(report.mimeType)) {
      const data = (await fs.readFile(report.storedPath)).toString("base64");
      blocks.push({ type: "document", source: { type: "base64", media_type: "application/pdf", data } });
    } else if (SUPPORTED_IMG.has(report.mimeType)) {
      const data = (await fs.readFile(report.storedPath)).toString("base64");
      blocks.push({
        type: "image",
        source: {
          type: "base64",
          media_type: report.mimeType as "image/png" | "image/jpeg" | "image/webp",
          data,
        },
      });
    } else {
      throw new Error(`Unsupported report type: ${report.mimeType}`);
    }

    const client = new Anthropic({ baseURL: process.env.ANTHROPIC_BASE_URL || undefined });
    const response = await client.messages.create({
      model: MODEL,
      max_tokens: 4000,
      system: systemPrompt(zh),
      messages: [{ role: "user", content: blocks }],
    });
    const text = response.content
      .filter((b): b is Anthropic.TextBlock => b.type === "text")
      .map((b) => b.text)
      .join("\n")
      .trim();

    await prisma.mobileReport.update({
      where: { id: reportId },
      data: { aiInterpretation: text || null, aiStatus: "done", aiError: null },
    });
  } catch (err) {
    await prisma.mobileReport.update({
      where: { id: reportId },
      data: { aiStatus: "failed", aiError: err instanceof Error ? err.message : String(err) },
    });
  }
}
