import Anthropic from "@anthropic-ai/sdk";
import { prisma } from "@/lib/db";

// AI generation of a WellnessPlan (饮食 + 锻炼) from a user's aggregated health
// record. Mirrors lib/report-ai.ts: fire-and-forget, writes the result back onto
// the WellnessPlan row and flips status to done/failed. The model is asked for a
// strict JSON { diet, exercise } object; on parse failure the raw text goes into
// dietText so the user still sees something.

const MODEL = process.env.ANTHROPIC_MODEL || "claude-opus-5";

function systemPrompt(zh: boolean): string {
  return zh
    ? `你是 Medicompass（迈缔康）的健康管理助手。基于用户的健康档案（基础信息、门诊/住院就诊、报告解读、监测指标、Apple 健康数据），为其制定个性化的「饮食」与「锻炼」建议。
要求：结合其诊断、指标偏离与用药情况，给出务实、可执行、循序渐进的方案；严格基于所给材料，不臆测、不编造，材料未提及处不强行给结论。
仅输出一个 JSON 对象，不要额外文字或代码块围栏，格式：
{"diet":"……","exercise":"……"}
其中 diet 为饮食建议（含总体原则 + 3-5 条具体可执行建议），exercise 为锻炼建议（含强度/频率/时长 + 注意事项）。每部分末尾附一句「本建议由 AI 依据所提供材料生成，不构成医疗诊断，请结合医生意见。」`
    : `You are the Medicompass health-management assistant. Based on the user's health record (basics, outpatient/inpatient visits, report readings, tracked vitals, Apple Health data), create a personalized "diet" and "exercise" plan.
Ground everything in the material: account for diagnoses, out-of-range metrics and medications; give practical, actionable, progressive guidance; do not fabricate; write nothing where the material is silent.
Output ONLY a single JSON object, no extra text or code fences, in the form:
{"diet":"…","exercise":"…"}
where diet is dietary guidance (overall principles + 3-5 concrete actionable tips) and exercise is exercise guidance (intensity/frequency/duration + precautions). End each section with: "This plan was generated by AI from the provided material, is not a medical diagnosis, and should be confirmed with your doctor."`;
}

function ageFrom(birthDate: Date | null): string {
  if (!birthDate) return "";
  const ms = Date.now() - birthDate.getTime();
  const years = Math.floor(ms / (365.25 * 24 * 3600 * 1000));
  return years > 0 && years < 130 ? `${years}` : "";
}

async function buildContext(userId: string, zh: boolean, healthContext?: string): Promise<string> {
  const [user, meds, visits, reports, vitals] = await Promise.all([
    prisma.mobileUser.findUnique({ where: { id: userId } }),
    prisma.mobileMedication.findMany({ where: { userId } }),
    prisma.mobileVisit.findMany({ where: { userId }, orderBy: { visitDate: "desc" }, take: 5 }),
    prisma.mobileReport.findMany({ where: { userId }, orderBy: { createdAt: "desc" }, take: 5 }),
    prisma.mobileVitalReading.findMany({ where: { userId }, orderBy: { measuredAt: "desc" }, take: 20 }),
  ]);

  const lines: string[] = [];
  if (user) {
    const age = ageFrom(user.birthDate);
    const basics = [
      user.gender ? (zh ? `性别 ${user.gender}` : `sex ${user.gender}`) : "",
      age ? (zh ? `年龄 ${age}` : `age ${age}`) : "",
      user.bloodType ? (zh ? `血型 ${user.bloodType}` : `blood ${user.bloodType}`) : "",
    ].filter(Boolean).join("，");
    if (basics) lines.push((zh ? "基础信息：" : "Basics: ") + basics);
    if (user.allergies) lines.push((zh ? "过敏史：" : "Allergies: ") + user.allergies);
    if (user.medicalHistory) lines.push((zh ? "既往史：" : "History: ") + user.medicalHistory);
  }
  if (meds.length) {
    lines.push(zh ? "用药计划：" : "Medications:");
    for (const m of meds) lines.push(`- ${zh ? m.nameZh : m.nameEn} ${m.dosage} ${zh ? m.timingZh : m.timingEn}`);
  }
  if (visits.length) {
    lines.push(zh ? "就诊记录（含门诊/住院）：" : "Visits (outpatient/inpatient):");
    for (const v of visits) {
      lines.push(`- ${v.visitDate.toISOString().slice(0, 10)} [${v.visitType}] ${v.department} ${v.diagnosis || v.hospital || ""}`.trim());
    }
  }
  if (reports.length) {
    lines.push(zh ? "报告解读：" : "Report readings:");
    for (const r of reports) {
      if (r.aiStatus === "done" && r.aiInterpretation) {
        lines.push(`- ${r.category}: ${r.aiInterpretation.replace(/\s+/g, " ").slice(0, 300)}`);
      }
    }
  }
  if (vitals.length) {
    lines.push(zh ? "监测指标：" : "Tracked vitals:");
    for (const r of vitals) {
      const sec = r.secondary != null ? `/${r.secondary}` : "";
      lines.push(`- ${r.kind} ${r.value}${sec} @ ${r.measuredAt.toISOString().slice(0, 10)}`);
    }
  }
  if (healthContext && healthContext.trim()) {
    lines.push(zh ? "Apple 健康数据：" : "Apple Health data:");
    lines.push(healthContext.trim());
  }
  return lines.join("\n") || (zh ? "（暂无记录）" : "(no records yet)");
}

export async function generateWellnessPlan(
  planId: string,
  userId: string,
  locale: string,
  healthContext?: string,
): Promise<void> {
  const zh = (locale || "").startsWith("zh");
  try {
    if (!process.env.ANTHROPIC_API_KEY) throw new Error("Missing ANTHROPIC_API_KEY");

    const context = await buildContext(userId, zh, healthContext);
    const client = new Anthropic({ baseURL: process.env.ANTHROPIC_BASE_URL || undefined });
    const msg = await client.messages.create({
      model: MODEL,
      max_tokens: 1200,
      system: systemPrompt(zh),
      messages: [
        { role: "user", content: (zh ? "以下是该用户的健康档案：\n" : "Here is the user's health record:\n") + context },
      ],
    });
    const text = msg.content
      .filter((b): b is Anthropic.TextBlock => b.type === "text")
      .map((b) => b.text)
      .join("")
      .trim();

    let diet = "";
    let exercise = "";
    // Model is asked for a bare JSON object; tolerate stray prose/fences.
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      try {
        const parsed = JSON.parse(jsonMatch[0]) as { diet?: string; exercise?: string };
        diet = (parsed.diet || "").trim();
        exercise = (parsed.exercise || "").trim();
      } catch {
        // fall through to raw
      }
    }
    if (!diet && !exercise) diet = text; // parse failed: keep raw so the user sees it

    await prisma.wellnessPlan.update({
      where: { id: planId },
      data: { dietText: diet, exerciseText: exercise, status: "done", error: null },
    });
  } catch (err) {
    await prisma.wellnessPlan.update({
      where: { id: planId },
      data: { status: "failed", error: err instanceof Error ? err.message : String(err) },
    });
  }
}
